=== AlfredoCodes-11/Lenguajes-De-Marcas/Unidad_01/banco.dtd
<!ELEMENT banco (sucursal+)>
<!ELEMENT sucursal (cuentas+)>
<!ATTLIST sucursal id NMTOKEN #REQUIRED>
<!ELEMENT cuentas (cliente+)>
<!ATTLIST cuentas id NMTOKEN #REQUIRED>
<!ELEMENT cliente (nombre,telefono)>
<!ATTLIST cliente dni NMTOKEN #IMPLIED>
<!ATTLIST cliente id NMTOKEN #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>

=== AlfredoCodes-11/Lenguajes-De-Marcas/Unidad_01/banco.xml
<?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE banco SYSTEM "banco.dtd">
<banco>
        <sucursal id="S001">
            <cuentas id="C001S1">
                <cliente dni="6544545J">
                    <nombre>Javier L칩pez</nombre>
                    <telefono>65456456</telefono>
                </cliente>
                <cliente dni="65444545G">
                    <nombre>Sara Gonz치lez</nombre>
                    <telefono>65456454</telefono>
                </cliente>
            </cuentas>
            <cuentas id="C002S1">
                <cliente dni="6544543D">
                    <nombre>Sergio P치ez</nombre>
                    <telefono>65456463</telefono>
                </cliente>
            </cuentas>
        </sucursal>
        <sucursal id="S002">
            <cuentas id="C001S2">
                <cliente id="56546434D">
                    <nombre>Natalia Mu침oz</nombre>
                    <telefono>65464747</telefono>
                </cliente>
            </cuentas>
        </sucursal>
    </banco>
