=== AlfredoCodes-11/Lenguajes-De-Marcas/Unidad_01/ejemplo.dtd
<!ELEMENT empresa (cliente+)>
<!ELEMENT cliente (nombre,dni,direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre id NMTOKEN #REQUIRED>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT direccion (calle,cp)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT cp (#PCDATA)>

=== AlfredoCodes-11/Lenguajes-De-Marcas/Unidad_01/ejemplo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "ejemplo.dtd">
<empresa xmlns:ubi="www.mipagina.es/ubi">
    <cliente>
        <nombre id="001">Alfredo codes SÃ¡nchez</nombre>
        <dni>654654654M</dni>
        <ubi:direccion>
            <calle>cnsdknfskld</calle>
            <cp>34535</cp>
        </ubi:direccion>
    </cliente>
    <cliente>
        <nombre id="002">dfsadfasgasg</nombre>
        <dni>987868968J</dni>
        <ubi:direccion>
            <calle>cngdgfskld</calle>
            <cp>342325</cp>
        </ubi:direccion>
    </cliente>
</empresa>
